[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc-version = "0.8.30"
optimizer = true
optimizer-runs = 200
via-ir = true

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
    "foundry-chainlink-toolkit/=lib/foundry-chainlink-toolkit/",
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/"

]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
